@extends('layouts.user_type')

@section('content')

<div>
  <div class="alert alert-secondary mx-4" role="alert">
    <span class="text-white">
      <strong>The Table Already Uses The Pagination!</strong> The Images generated by my random code, not fetched from the database, don't know why i'd do that, but that's looks nice for me
    </span>
  </div>

  <div class="row">
    <div class="col-12">
      <div class="card mb-4 mx-4">
        <div class="card-header pb-0">
          <div class="d-flex flex-row justify-content-between">
            <div>
              <h5 class="mb-0">All Transactions</h5>
            </div>
            <a href="{{ route('transactions.create') }}" class="btn bg-gradient-primary btn-sm mb-0" type="button">+&nbsp; New Transaction</a>
          </div>
        </div>
        <div class="card-body px-0 pt-0 pb-2">
          <div class="table-responsive p-0">
            <table class="table align-items-center mb-0">
              <thead>
                <tr>
                  <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">
                    ID
                  </th>
                  <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">
                    Photo
                  </th>
                  <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">
                    Kategori
                  </th>
                  <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">
                    Nominal
                  </th>
                  <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">
                    Tujuan
                  </th>
                  <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">
                    Nama Akun
                  </th>
                  <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">
                    Action
                  </th>
                </tr>
              </thead>
              <tbody>
                @foreach ($transactions as $item)
                <tr>
                  <td class="ps-4">
                    <a href="{{ route('transactions.show', $item->id) }}" class="text-xs font-weight-bold mb-0">{{ $item->id }}</a>
                  </td>
                  <td>
                    <div>
                      <img src="{{ '../assets/img/team-' . Arr::random(['1', '2', '3', '4']) . '.jpg' }}" class="avatar avatar-sm me-3">
                    </div>
                  </td>
                  <td class="text-center">
                    <p class="text-xs font-weight-bold mb-0">{{ $item->kategori }}</p>
                  </td>
                  <td class="text-center">
                    <p class="text-xs font-weight-bold mb-0">{{ $item->nominal }}</p>
                  </td>
                  <td class="text-center">
                    <p class="text-xs font-weight-bold mb-0">{{ $item->tujuan }}</p>
                  </td>
                  <td class="text-center">
                    <p class="text-xs font-weight-bold mb-0">{{ $item->account_id }}</p>
                  </td>
                  <td class="text-center">
                    <a href="{{ route('transactions.edit', $item->id) }}" class="mx-3" data-bs-toggle="tooltip" data-bs-original-title="Edit account">
                      <i class="fas fa-user-edit text-secondary"></i>
                    </a>
                    <a href="{{ route('transactions.destroy', $item->id) }}" data-method="delete" class="mx-3" data-bs-toggle="tooltip" data-bs-original-title="Delete account" rel="nofollow">
                      <i class="cursor-pointer fas fa-trash text-secondary"></i>
                    </a>
                  </td>
                </tr>
                @endforeach
              </tbody>
            </table>
          </div>
        </div>
      </div>
      {{ $transactions->links() }}
    </div>
  </div>
</div>

@endsection
@section('script')
@endsection